replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 10Gi
  storageClass: managed-csi

keyVault:
  name: kv-aks-dev-aayush1290
  tenantId: aac42910-b03a-44c1-b372-7cee5c67a2d5

  #  THIS MUST BE KUBELET CLIENT ID
  identityClientId: 75e65c28-33d2-4706-9468-cc99877c4215

  secrets:
    rootPassword: mysql-root-password1
    database: mysql-database1
