apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-azure-kv
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}

    # ðŸ”¥ REQUIRED for multi-identity AKS
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.identityClientId }}

    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secrets.rootPassword }}
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secrets.database }}
          objectType: secret
