apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-azure-kv
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.keyVault.tenantId }}
    objects: |
      array:
        - |
          objectName: {{ .Values.keyVault.secrets.rootPassword }}
          objectType: secret
        - |
          objectName: {{ .Values.keyVault.secrets.database }}
          objectType: secret
