replicaCount: 1

image:
  repository: acrdevayu2026512.azurecr.io/spring-crud
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

mysql:
  host: mysql
  port: 3306

keyVault:
  secrets:
    rootPassword: mysql-root-password
