name: CI - Build and Push Images to ACR

on:
  push:
    branches:
      - main
    paths:
      - AngularCRUD/**
      - SpringCRUD/**
      - .github/workflows/ci.yml

env:
  ACR_NAME: acrdevayu2026512
  ACR_LOGIN_SERVER: acrdevayu2026512.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      # -------------------------
      # Build & Push Spring Boot
      # -------------------------
      - name: Build Spring Boot image
        run: |
          docker build -t $ACR_LOGIN_SERVER/spring-crud:$IMAGE_TAG ./SpringCRUD

      - name: Push Spring Boot image
        run: |
          docker push $ACR_LOGIN_SERVER/spring-crud:$IMAGE_TAG

      # -------------------------
      # Build & Push Angular
      # -------------------------
      - name: Build Angular image
        run: |
          docker build -t $ACR_LOGIN_SERVER/angular-crud:$IMAGE_TAG ./AngularCRUD

      - name: Push Angular image
        run: |
          docker push $ACR_LOGIN_SERVER/angular-crud:$IMAGE_TAG
